name: Execution Bash Script Yt
on:
    workflow_dispatch:
        inputs:
            youtube_url:
                description: 'URL de la vidéo'
                required: true


jobs:
    get_thumnail:
        runs-on: macos-latest
        steps:
        - name: checkout repo
          uses: actions/checkout@v4

        - name: give permissions to the script
          run: chmod +x get_thumbnail.sh

        - name: Execute script
          run: ./get_thumbnail.sh ${{ inputs.youtube_url }}

        - name: List files in thumbnails directory
          run: |
            echo "Listing files in thumbnails directory:"
            ls -l thumbnails

        - name: push artefact
          uses: actions/upload-artifact@v4.6.2
          with:
           name: youtube thumbnail
           path: thumbnails*.jpg