name: Exécuter un script Bash

on:
  workflow_dispatch:  # Permet de lancer ce workflow manuellement

jobs:
  run-script:
    runs-on: ubuntu-latest  # Environnement sur lequel le job sera exécuté

    steps:
      # Étape 1 : Vérifier le code du dépôt
      - name: Vérifier le code du dépôt
        uses: actions/checkout@v4.2.2  # Utilisation de la version stable v4

      # Étape 2 : Donner les permissions d'exécution au script
      - name: Donner les permissions d'exécution au script
        run: chmod +x ./get_thumbnail.sh

      # Étape 3 : Exécuter le script avec l'URL de la vidéo
      - name: Exécuter le script get_thumbnail.sh
        run: ./get_thumbnail.sh https://www.youtube.com/watch?v=MCL8DpoM9fs&t=18s

      # Étape 4 : Vérifier que le fichier thumbnail.jpg est généré
      - name: Lister les fichiers du répertoire
        run: ls -l  # Affiche la liste des fichiers dans le répertoire courant

      # Étape 5 : Télécharger l'artefact généré (vérifie que thumbnails.jpg existe)
      - name: Télécharger l'artefact généré
        uses: actions/upload-artifact@v4.6.2
        with:
          name: download video yt
          path: thumbnails.jpg