name: Exécuter un script Bash

on:
  workflow_dispatch:  # Permet de lancer ce workflow manuellement

jobs:
  run-script:
    runs-on: ubuntu-latest  # Environnement sur lequel le job sera exécuté

    steps:
      # Étape 1 : Vérifier le code du dépôt
      - name: Vérifier le code du dépôt
        uses: actions/checkout@v4  # Utilisation de la version stable v4

      # Étape 2 : Donner les permissions d'exécution au script
      - name: Donner les permissions d'exécution au script
        run: chmod +x ./get_thumbnail.sh

      # Étape 3 : Exécuter le script avec l'URL de la vidéo
      - name: Exécuter le script get_thumbnail.sh
        run: ./get_thumbnail.sh "https://www.youtube.com/watch?v=MCL8DpoM9fs&t=18s" uploads

      # Étape 4 : Télécharger l'artefact généré
      - name: Télécharger l'artefact généré
        uses: actions/upload-artifact@v4.6.2  # Utilisation de la version stable v4
        with:
          name: thumbnail-artifact
          path: uploads